name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        repo-token: secrets.GITHUB_TOKEN
        issue-message: Welcome! 
        pr-message: LGTM
